# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpdq < Formula
  desc "A cli tool to parse MPEG-DASH manifests"
  homepage "https://github.com/jfreeland/mpdq"
  version "0.1.0"
  bottle :unneeded
  depends_on :linux

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jfreeland/mpdq/releases/download/v0.1.0/mpdq_0.1.0_linux_arm64.tar.gz"
    sha256 "b80607c7f4b7f1d9d579f5a95c794f08ba64fcbd7983286589098e353efb0d06"
  end

  def install
    bin.install "mpdq"
  end
end
