# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpdq < Formula
  desc "A cli tool to parse MPEG-DASH manifests"
  homepage "https://github.com/jfreeland/mpdq"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jfreeland/mpdq/releases/download/v0.1.1/mpdq_0.1.1_darwin_amd64.tar.gz"
    sha256 "4b30588b6fdd3051a82c1006cda8e2c3ac7510af50516e25142d21960dfb0ac2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jfreeland/mpdq/releases/download/v0.1.1/mpdq_0.1.1_linux_amd64.tar.gz"
    sha256 "97ee25a1deb2a8bbad6dd5fe8864b2f3e94823fd529c33b5e99c0164641be3d0"
  end

  def install
    bin.install "mpdq"
  end
end
