# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpdq < Formula
  desc "A cli tool to parse MPEG-DASH manifests"
  homepage "https://github.com/jfreeland/mpdq"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jfreeland/mpdq/releases/download/v0.1.1/mpdq_0.1.1_darwin_amd64.tar.gz"
    sha256 "bf26e4cbc9718241d9a87d071d3dbccd489672daf3a2832ced244ab874e2b576"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jfreeland/mpdq/releases/download/v0.1.1/mpdq_0.1.1_linux_amd64.tar.gz"
    sha256 "cfbfb7f9e78430937bf221964e0329f4e4a539bf4f06858b148ac03b0095b9f0"
  end

  def install
    bin.install "mpdq"
  end
end
